<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.1.0 setup script
 * Date: Thu, 12 Dec 2013 22:36:48 +0400
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'mysql://127.4.246.2:3306/';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'adminbeM5Fgi';
$cfg['Servers'][$i]['password'] = 'HbQ7Sc95J9rD';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['DefaultLang'] = 'ru';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '52aa01a254d007.62368180';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>